const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const pkgDir = path.resolve(__dirname, '../pkg');

// 1. Clean previous build
if (fs.existsSync(pkgDir)) {
    fs.rmSync(pkgDir, { recursive: true, force: true });
}

// 2. Build for Node.js (CommonJS + fs)
console.log('🏗️  Building for Node.js...');
execSync('wasm-pack build --target nodejs --out-dir pkg/node --scope bect -- --features wasm', { stdio: 'inherit', cwd: path.resolve(__dirname, '..') });

// 3. Build for Web (ESM + fetch)
console.log('🏗️  Building for Web...');
execSync('wasm-pack build --target web --out-dir pkg/web --scope bect -- --features wasm', { stdio: 'inherit', cwd: path.resolve(__dirname, '..') });

// 3.5. Minify JS Glue Code
console.log('📉 Minifying JS glue code...');

const getFileSize = (filePath) => {
    try {
        return fs.statSync(filePath).size;
    } catch (e) {
        return 0;
    }
};

const formatSize = (bytes) => (bytes / 1024).toFixed(2) + ' KB';

try {
    const webFile = path.join(pkgDir, 'web/tanggalan.js');
    const nodeFile = path.join(pkgDir, 'node/tanggalan.js');
    const webSizeBefore = getFileSize(webFile);
    const nodeSizeBefore = getFileSize(nodeFile);

    // Minify Web build (ESM) - use --module to handle ES6 imports/exports
    execSync('npx terser pkg/web/tanggalan.js -o pkg/web/tanggalan.js --compress --mangle --module', { stdio: 'inherit', cwd: path.resolve(__dirname, '..') });
    // Minify Node build (CommonJS)
    execSync('npx terser pkg/node/tanggalan.js -o pkg/node/tanggalan.js --compress --mangle', { stdio: 'inherit', cwd: path.resolve(__dirname, '..') });

    console.log(`   Web JS:  ${formatSize(webSizeBefore)} -> ${formatSize(getFileSize(webFile))}`);
    console.log(`   Node JS: ${formatSize(nodeSizeBefore)} -> ${formatSize(getFileSize(nodeFile))}`);
} catch (e) {
    console.warn('⚠️  Minification failed. Ensure "terser" is installed or npx is available.');
}

// 4. Create unified package.json
console.log('📦 Configuring unified package.json...');
// Read the package.json generated by wasm-pack (using the web one as a base)
const basePkg = JSON.parse(fs.readFileSync(path.join(pkgDir, 'web/package.json'), 'utf8'));

const unifiedPkg = {
    ...basePkg,
    // Include both build directories in the package
    files: ['node', 'web'],
    // Default entry points
    main: './node/tanggalan.js',
    module: './web/tanggalan.js',
    types: './web/tanggalan.d.ts',
    // Conditional exports for modern bundlers and Node.js
    exports: {
        ".": {
            "node": "./node/tanggalan.js",
            "import": "./web/tanggalan.js",
            "default": "./web/tanggalan.js"
        }
    },
    sideEffects: false,
    publishConfig: {
        access: "public"
    }
};

fs.writeFileSync(path.join(pkgDir, 'package.json'), JSON.stringify(unifiedPkg, null, 2));

// 5. Copy README and LICENSE to the root of pkg
const rootDir = path.resolve(__dirname, '..');

// Copy LICENSE
if (fs.existsSync(path.join(rootDir, 'LICENSE'))) {
    fs.copyFileSync(path.join(rootDir, 'LICENSE'), path.join(pkgDir, 'LICENSE'));
}

// Copy docs/JS.md as README.md for the NPM package
if (fs.existsSync(path.join(rootDir, 'docs/JS.md'))) {
    fs.copyFileSync(path.join(rootDir, 'docs/JS.md'), path.join(pkgDir, 'README.md'));
}

// 6. Remove redundant README and LICENSE from subdirectories
['node', 'web'].forEach(sub => {
    ['README.md', 'LICENSE'].forEach(file => {
        const filePath = path.join(pkgDir, sub, file);
        if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
        }
    });
});

console.log('✅ Build successful! You can now run "npm publish" inside the pkg/ directory.');